[project]
name = "nanobot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.14.2"
dependencies = [
    "lms-mcp",
    "nanobot-ai>=0.1.4.post5",
    "nanobot-webchat",
]

[tool.uv.sources]
lms-mcp = { path = "/app/mcp", editable = true }
nanobot-webchat = { path = "/app/nanobot-websocket-channel", editable = true }
